"""
Runnable Branch :
    - RunnableBranch is the if / elif / else style control-flow component in LangChain.
    - It routes the input to different chains or runnables based on custom conditions.
    - The first matching condition wins.
    - If no condition matches, a default branch can be used.

    Goal:
    - RunnableBranch = conditional chains.
    - Example routing:
        - complaint -> customer
        - refund -> database
        - general query -> chatbot
    - One possible flow:
        email -> prompt -> llm -> RunnableBranch -> complaint / refund / general
    - Another branch example:
        topic -> prompt -> llm -> parse
        - if output > 500 words -> summarize
        - if output < 500 words -> print
"""

from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableBranch, RunnableLambda, RunnableSequence, RunnablePassthrough

load_dotenv()

prompt1 = PromptTemplate(
    template='Write a detailed report on {topic}',
    input_variable=['topic']
)

prompt2 = PromptTemplate(
    template='Summarize the following {text}',
    input_variable=['text']
)

model = ChatOpenAI()

parser = StrOutputParser()

# This first chain always runs.
# Flow:
#   user topic -> prompt1 -> model -> parser -> report text
report_gen_chain = RunnableSequence(prompt1, model, parser).with_config(
    # run_name and tags do not print in the terminal automatically.
    # They are useful when you use LangChain callbacks / LangSmith tracing.
    run_name="generate_detailed_report",
    tags=["report-generation"],
)

# This chain runs only when the generated report is long enough.
# It takes the report text from report_gen_chain and summarizes it.
summarize_chain = RunnableSequence(prompt2, model, parser).with_config(
    run_name="summarize_branch",
    tags=["branch:summarize"],
)

# This is the default branch.
# RunnablePassthrough simply returns the input unchanged.
# In this example, if the report is not more than 100 words, we keep it as-is.
passthrough_chain = RunnablePassthrough().with_config(
    run_name="passthrough_branch",
    tags=["branch:passthrough"],
)


def print_branch_name(name):
    # RunnableBranch itself chooses the branch, but it does not print the
    # branch name to the terminal. This helper creates a small Runnable that
    # prints the selected branch name and then returns the same input unchanged.
    def _print_and_pass_through(x):
        print(f"Running branch: {name}")
        return x

    # RunnableLambda converts a normal Python function into a LangChain Runnable.
    # Because it returns x unchanged, it can be placed before any branch using `|`.
    return RunnableLambda(_print_and_pass_through).with_config(
        run_name=f"log_{name}_branch",
        tags=[f"branch-log:{name}"],
    )


# RunnableBranch works like if / elif / else:
#   1. Each tuple is: (condition, runnable_to_execute_if_condition_is_true)
#   2. The first matching condition wins.
#   3. The final runnable without a condition is the default else branch.
#
# Here, the input to this branch is the report text generated by report_gen_chain.
branch_chain = RunnableBranch(
    # If the report has more than 100 words, print the branch name and summarize it.
    (lambda x: len(x.split()) > 5000, print_branch_name("summarize") | summarize_chain),
    # Otherwise, print the branch name and return the report unchanged.
    print_branch_name("passthrough") | passthrough_chain,
).with_config(
    run_name="report_length_branch",
    tags=["branch-router"],
)

# Final flow:
#   topic -> generate report -> choose summarize or passthrough branch
final_chain = RunnableSequence(report_gen_chain, branch_chain)

result = final_chain.invoke(
    {'topic': 'Mid Level Agentic AI Engineer package in Lakhs'},
    config={
        # This names the top-level run in tracing tools.
        # It does not print automatically in the terminal.
        "run_name": "runnable_branch_demo",
        "tags": ["demo", "runnable-branch"],
    },
)

print(result)
